version: "3.8" # Zorg ervoor dat dit correct is voor je versie

services:
  backend:
    build:
      context: ./Backend
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Database:/app/Database
    environment:
      - DATABASE_PATH=/app/Database/Database.db
    depends_on:
      - database

  frontend:
    build:
      context: ./Frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./Frontend/my-app:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  database:
    image: nouchka/sqlite3:latest
    volumes:
      - ./Database:/data
    command: sqlite3 /data/Database.db


